{
   "openapi":"3.0.1",
   "info":{
      "title":"OpenAPI definition",
      "version":"v0"
   },
   "servers":[
      {
         "url":"http://localhost:9081",
         "description":"Generated server url"
      }
   ],
   "paths":{
      "/seller/delete/{productId}":{
         "delete":{
            "tags":[
               "product-command-controller"
            ],
            "operationId":"deleteProduct",
            "parameters":[
               {
                  "name":"productId",
                  "in":"path",
                  "required":true,
                  "schema":{
                     "type":"integer",
                     "format":"int64"
                  }
               }
            ],
            "responses":{
               "200":{
                  "description":"default response",
                  "content":{
                     "*/*":{
                        "schema":{
                           "type":"string"
                        }
                     }
                  }
               }
            }
         }
      },
      "/seller/add-product":{
         "post":{
            "tags":[
               "product-command-controller"
            ],
            "operationId":"postProduct",
            "requestBody":{
               "content":{
                  "application/json":{
                     "schema":{
                        "$ref":"#/components/schemas/ProductCommandDTO"
                     }
                  }
               }
            },
            "responses":{
               "200":{
                  "description":"default response",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Product"
                        }
                     }
                  }
               }
            }
         }
      },
      "/report/show-bids/{productId}":{
         "get":{
            "tags":[
               "product-query-controller"
            ],
            "operationId":"showBids",
            "parameters":[
               {
                  "name":"productId",
                  "in":"path",
                  "required":true,
                  "schema":{
                     "type":"integer",
                     "format":"int64"
                  }
               }
            ],
            "responses":{
               "200":{
                  "description":"default response",
                  "content":{
                     "*/*":{
                        "schema":{
                           "type":"array",
                           "items":{
                              "$ref":"#/components/schemas/ProductBidQueryDTO"
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   },
   "components":{
      "schemas":{
         "ProductCommandDTO":{
            "required":[
               "productName"
            ],
            "type":"object",
            "properties":{
               "productName":{
                  "maxLength":30,
                  "minLength":5,
                  "type":"string"
               },
               "shortDescription":{
                  "type":"string"
               },
               "detailedDescription":{
                  "type":"string"
               },
               "category":{
                  "type":"string",
                  "enum":[
                     "Painting",
                     "Sculptor",
                     "Ornament"
                  ]
               },
               "startingPrice":{
                  "type":"integer",
                  "format":"int64"
               },
               "bidEndDate":{
                  "type":"string",
                  "format":"date"
               },
               "seller":{
                  "$ref":"#/components/schemas/UserInfoCommandDTO"
               }
            }
         },
         "UserInfoCommandDTO":{
            "required":[
               "email",
               "firstName",
               "lastName",
               "phone"
            ],
            "type":"object",
            "properties":{
               "firstName":{
                  "maxLength":30,
                  "minLength":5,
                  "type":"string"
               },
               "lastName":{
                  "maxLength":25,
                  "minLength":3,
                  "type":"string"
               },
               "address":{
                  "type":"string"
               },
               "city":{
                  "type":"string"
               },
               "state":{
                  "type":"string"
               },
               "pin":{
                  "type":"string"
               },
               "phone":{
                  "maximum":10,
                  "minimum":10,
                  "type":"integer",
                  "format":"int64"
               },
               "email":{
                  "type":"string"
               },
               "userType":{
                  "type":"string",
                  "enum":[
                     "BUYER",
                     "SELLER"
                  ]
               }
            }
         },
         "Product":{
            "type":"object",
            "properties":{
               "id":{
                  "type":"integer",
                  "format":"int64"
               },
               "productName":{
                  "type":"string"
               },
               "shortDescription":{
                  "type":"string"
               },
               "detailedDescription":{
                  "type":"string"
               },
               "category":{
                  "type":"string",
                  "enum":[
                     "Painting",
                     "Sculptor",
                     "Ornament"
                  ]
               },
               "startingPrice":{
                  "type":"integer",
                  "format":"int64"
               },
               "bidEndDate":{
                  "type":"string",
                  "format":"date"
               },
               "userInformation":{
                  "$ref":"#/components/schemas/UserInformation"
               }
            }
         },
         "UserInformation":{
            "type":"object",
            "properties":{
               "id":{
                  "type":"integer",
                  "format":"int64"
               },
               "firstName":{
                  "type":"string"
               },
               "lastName":{
                  "type":"string"
               },
               "address":{
                  "type":"string"
               },
               "city":{
                  "type":"string"
               },
               "state":{
                  "type":"string"
               },
               "pin":{
                  "type":"string"
               },
               "phone":{
                  "type":"integer",
                  "format":"int64"
               },
               "email":{
                  "type":"string"
               },
               "userType":{
                  "type":"string",
                  "enum":[
                     "BUYER",
                     "SELLER"
                  ]
               }
            }
         },
         "ProductBidQueryDTO":{
            "type":"object",
            "properties":{
               "id":{
                  "type":"integer",
                  "format":"int64"
               },
               "productName":{
                  "type":"string"
               },
               "shortDescription":{
                  "type":"string"
               },
               "detailedDescription":{
                  "type":"string"
               },
               "category":{
                  "type":"string",
                  "enum":[
                     "Painting",
                     "Sculptor",
                     "Ornament"
                  ]
               },
               "startingPrice":{
                  "type":"integer",
                  "format":"int64"
               },
               "bidEndDate":{
                  "type":"string",
                  "format":"date"
               },
               "bidAmount":{
                  "type":"integer",
                  "format":"int64"
               },
               "buyerFirstName":{
                  "type":"string"
               },
               "buyerLastName":{
                  "type":"string"
               },
               "buyerAddress":{
                  "type":"string"
               },
               "buyerCity":{
                  "type":"string"
               },
               "buyerState":{
                  "type":"string"
               },
               "buyerPin":{
                  "type":"string"
               },
               "buyerPhone":{
                  "type":"integer",
                  "format":"int64"
               },
               "buyerEmail":{
                  "type":"string"
               }
            }
         }
      }
   }
}